dist: xenial
language: minimal
sudo: required
addons:
  apt:
    packages:
    - p7zip-full
    - mtools
    - jq
    - u-boot-tools
    - html-xml-utils
    - squashfs-tools
    - bsdtar
    - axel
script:
- make build_armbian=y build
- ls -l output
deploy:
  provider: releases
  api_key:
    secure: TJzJyqjTAOgKxfc5AieiJSNN0Al+RAQwcM3R3r1K16xJIUf9SWQhCI9t94xRKP0i/UDGR7kcYMU2VTWz89OMUFQaHlSa4SfzMkUi1oMNDT5IUBL3f5DUMvmOjH/kME5I9M8qpUujqOidNUQQmNdK1Yhg4SXsgsEOwiouY7tBP4aTnf4q6vj/xYaiFgWdcM6vQWN4RuV/DGIvNVmfOFZiblWP8t7i+0L/Q4mnSp04ePVPPMmFFGpSOi9Z/4U8o7Lbtazp2b4aO+z8kmM0KLP5rTb29GK+hH6LiazyN3y/JST2C00Lyu2DYWsB+CnX1PvG3bsVEV1fCUdtzeGW9jFLGhI3iJv+87FDzyaxytoENs66j9hTL6qYiuUToSNyVM1qoPFLfBx4PD5eaAC5nIxaaKZzLPfdv0xG/By/NryGoL5ZGRIMbzKGKCMQMGXeGjCTXViKs5SMSGNNh8dCRzTP4NpAi2G4/HrWN2SdJ/4HOQ0WebPyEUFCjxUmshti/44c7uWR8LsdTA5tE2NGWi2J6VgmVCqi5JOPesX6wpIisBRb+MU8bbnEddkb2a6U1bHO+z1rkuktrzY6lL/AXiDjERoeo40b0H2wBbJJME+Cts3+y8TBPIt4qm2RY5r5sLOiS+o/eyeuIYCtU+BKfOMBVNH01Km/zra8R/V+6cpnvJ8=
  skip_cleanup: true
  overwrite: true
  file_glob: true
  file: output/*.sha
  on:
    repo: qijianjun/build-beikeyun
    tags: true
