dist: xenial
language: minimal
sudo: required
addons:
  apt:
    packages:
    - p7zip-full
    - mtools
    - jq
    - u-boot-tools
    - html-xml-utils
    - squashfs-tools
    - bsdtar
    - axel
script:
- make build_armbian=y build
- ls -l output
deploy:
  provider: releases
  api_key:
    secure: lH7FM9E0biJJzQxNTinKz/8VXk4tZAd5Tz9ZeLKfk//5PKbFaHMtMc4ymjzlIeYp/no/iHU22BjXRMlV6eITC9AX8Y+O72cO+rgatT8iMHLnSEvLV1XSgynTAlY++YfIe/18wqQpN4FbsX8R2pywEnY9NO42lDC/GY7rRCo3VkRlkBIgpA0mXjnA/ekV1/eJ26bSOYzJvHfqRUYSwB5vsfu/7ctCEy4KjjiXW7GCPYtpWn8FZjUG0DtYWVBt/OA9PyHkSVl3TuoRd2fmh99y4VpHjLojW9pGL6Q4WEYMWaibsMNV5Zc5E3ErSTo+pAcs7h5mNjb/FPJ+Ca+ev4JuDoxz/LfG7HCZJjtXmIDxvUYc/gz5oY/DLL8zTjns1Y0NnzMhCk/7ah25Esa5zSOXQWorRLwFKrupd1CuQU2lsAKCwPFH8va0sLvTRNINOBAeUlvyAxNGjgJmlsTTXXk2maSwlOBTb/2+L7vWuA7ERzJiLov7n2HVPL2xkZh8kOcgAUFMtKCxRhvSzxzVRTUzJjfyYOpdYKu73hxNTIO4N/OaANk/uHCG7uHR9+79RtGfm5CHanODIvtCvlvmpQ1Ubo2d6uqRLuqS1Y+j6uLmjmcKwFqSFqrjaT0Ne8DsgbF9fXdznVo0xAXjlnr+Gs84xFZPRog5TRjFGEn+Kmh2sm8=
  skip_cleanup: true
  overwrite: true
  file_glob: true
  file: output/*.sha
  on:
    repo: qijianjun/build-beikeyun
    tags: true
env:
  global:
    secure: lH7FM9E0biJJzQxNTinKz/8VXk4tZAd5Tz9ZeLKfk//5PKbFaHMtMc4ymjzlIeYp/no/iHU22BjXRMlV6eITC9AX8Y+O72cO+rgatT8iMHLnSEvLV1XSgynTAlY++YfIe/18wqQpN4FbsX8R2pywEnY9NO42lDC/GY7rRCo3VkRlkBIgpA0mXjnA/ekV1/eJ26bSOYzJvHfqRUYSwB5vsfu/7ctCEy4KjjiXW7GCPYtpWn8FZjUG0DtYWVBt/OA9PyHkSVl3TuoRd2fmh99y4VpHjLojW9pGL6Q4WEYMWaibsMNV5Zc5E3ErSTo+pAcs7h5mNjb/FPJ+Ca+ev4JuDoxz/LfG7HCZJjtXmIDxvUYc/gz5oY/DLL8zTjns1Y0NnzMhCk/7ah25Esa5zSOXQWorRLwFKrupd1CuQU2lsAKCwPFH8va0sLvTRNINOBAeUlvyAxNGjgJmlsTTXXk2maSwlOBTb/2+L7vWuA7ERzJiLov7n2HVPL2xkZh8kOcgAUFMtKCxRhvSzxzVRTUzJjfyYOpdYKu73hxNTIO4N/OaANk/uHCG7uHR9+79RtGfm5CHanODIvtCvlvmpQ1Ubo2d6uqRLuqS1Y+j6uLmjmcKwFqSFqrjaT0Ne8DsgbF9fXdznVo0xAXjlnr+Gs84xFZPRog5TRjFGEn+Kmh2sm8=
