dist: xenial
language: minimal
sudo: required
addons:
  apt:
    packages:
    - p7zip-full
    - mtools
    - jq
    - u-boot-tools
    - html-xml-utils
    - squashfs-tools
    - bsdtar
    - axel
script:
- make build_armbian=y build
- ls -l output
deploy:
  provider: releases
  api_key:
    secure: P0/mmQokjj6Zzx1qmnIu7uOLgov9dnMsfOmGNLy81GVe7lIw+sgoWf6O6bAM3Dh8sN0/5/t5usvOp3mAkr9Gii5cpK+VVolHO8ueDBobTRtATP6eFlnwpOJNeqwQ/yOuvhAzJlbO7W1SCZnuigMPwMuAOnOrHBp7SYPNo17nw0iWRZ+fLq2A6BWjPOOQLJyI5WjdFkuZlsFqUnuIdq6RYCMAAVED6ZWb0vFNmUtf9oQAw+lBbmZ2kzGU3rJochDaL13YEDAz84Zx5BaJbZ84CVGPY6dinYeJE8lXVTum+Hcky0LFyqaMS9vncbqF8+Zs5XlePAzdniXVZ3OSmiN9Arnv3iSl4MTajfoCXQtJUeU3GKdcniJqeelIoTV5FKUf6yS8dpLHK3CiS+G2PeIj5HIvTpZhHnqIxLl6j3DF50BqAc081MMz8vl/Gt+9IybezL1NaTSTnIipfME1jdMZ8B/ofnpZcg6h9eIe//O5af7boUAAgrYvFDC6eFt4CFelZXEc4Ytaxqomw7cHmJAVILSjhXBb5q6jnkt3qZQeMIwL/duU51iAubRsWmVAvH45Ts94joL+IC/XQo1tN/dAm01O1TJr2DEDZsAPsXnpD7uodrYaHPVNJemvMAotMfekeygb6Uk2nQupkqzQt6AUPoV+06ogS5IUi2HUVrEDVaI=
  skip_cleanup: true
  overwrite: true
  file_glob: true
  file: output/*.xz
  on:
    repo: qijianjun/build-beikeyun
    tags: true
env:
  global:
    secure: lH7FM9E0biJJzQxNTinKz/8VXk4tZAd5Tz9ZeLKfk//5PKbFaHMtMc4ymjzlIeYp/no/iHU22BjXRMlV6eITC9AX8Y+O72cO+rgatT8iMHLnSEvLV1XSgynTAlY++YfIe/18wqQpN4FbsX8R2pywEnY9NO42lDC/GY7rRCo3VkRlkBIgpA0mXjnA/ekV1/eJ26bSOYzJvHfqRUYSwB5vsfu/7ctCEy4KjjiXW7GCPYtpWn8FZjUG0DtYWVBt/OA9PyHkSVl3TuoRd2fmh99y4VpHjLojW9pGL6Q4WEYMWaibsMNV5Zc5E3ErSTo+pAcs7h5mNjb/FPJ+Ca+ev4JuDoxz/LfG7HCZJjtXmIDxvUYc/gz5oY/DLL8zTjns1Y0NnzMhCk/7ah25Esa5zSOXQWorRLwFKrupd1CuQU2lsAKCwPFH8va0sLvTRNINOBAeUlvyAxNGjgJmlsTTXXk2maSwlOBTb/2+L7vWuA7ERzJiLov7n2HVPL2xkZh8kOcgAUFMtKCxRhvSzxzVRTUzJjfyYOpdYKu73hxNTIO4N/OaANk/uHCG7uHR9+79RtGfm5CHanODIvtCvlvmpQ1Ubo2d6uqRLuqS1Y+j6uLmjmcKwFqSFqrjaT0Ne8DsgbF9fXdznVo0xAXjlnr+Gs84xFZPRog5TRjFGEn+Kmh2sm8=
