name: Build Beikeyun

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'

env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-16.04

    steps:
    - name: Initialization environment
      run: sudo apt-get install p7zip-full mtools jq u-boot-tools html-xml-utils squashfs-tools bsdtar axel -y

    - name: Bilud Armbian
      run: |
        make build_armbian=y build
        ls -l output

    - name: Check space usage
      if: (!cancelled())
      run: df -hT

    - name: Upload out directory
      uses: actions/upload-artifact@main
      with:
        name: output
        path: out/
