name: Build Beikeyun

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/build.yml'
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Initialization environment
      run: |
        sudo apt-get update
        sudo apt-get upgrade -y
        sudo apt-get install p7zip-full mtools jq u-boot-tools html-xml-utils squashfs-tools bsdtar axel -y

    - name: Bilud Armbian
      run: |
        make build_armbian=y build

    - name: Upload output directory
      uses: actions/upload-artifact@main
      with:
        name: output
        path: output/
